### PR TITLE
[C#] SOLID Principles revamp

### PR DESCRIPTION
**Pull request by YoussefWaelMohamedLotfy**
Continuing with the revamps in #18, this is the implementation of SOLID Principles.

## Changes implemented

- Created a dedicated `SOLID` project, with an example in `Program.cs` to show demo code.
- Sealed all concrete classes.
- Use File-Scoped namespaces, resulting in one less indentation level.
- XML Documentation on main classes and methods
- Updated `Order` class to use proper access modifiers and properties.

## Work to do

- [x] Add example code to `Program.cs` do show how SOLID can help in writing maintainable code.

@mahyoussef Looking forward to hearing your feedback.

### CODE REVIEW

**Comment by mahyoussef** [comment]
There's conflict inside the dotnet.sln file @YoussefWaelMohamedLotfy 
Also, I have a question: would that solution affect people who have older versions of C#? 

If so, I believe we need to address those kind of questions or setup in a README.MD file inside C# directory

**Comment by YoussefWaelMohamedLotfy** [comment]
> There's conflict inside the dotnet.sln file @YoussefWaelMohamedLotfy Also, I have a question: would that solution affect people who have older versions of C#?
> 
> If so, I believe we need to address those kind of questions or setup in a README.MD file inside C# directory

@mahyoussef Conflict resolved 👍🏻 You can proceed with merging this so I can fix the other conflict in #30

The Solution File `.sln` is related to Visual Studio. The solution is working using latest Visual Studio 2022. We can ask for help from the community to test the solution on older versions (I don't have one installed now), and I will be posting for help on X (Formerly Twitter). As for the individual projects, they are working on the latest .NET (8 at the time of writing this comment) and requires that learners to have .NET 8 installed on their machine. If you are concerned with compatibility, we can also add support for active versions of .NET 6 and 7 but will need some work as features from .NET 8 are used and will need to count for old versions.

**Comment by mahyoussef** [comment]
I believe adding these information in a README.MD file would be perfect so in order to run the project in Vs, make sure to have the most recent versions or something like that 😍

**Comment by YoussefWaelMohamedLotfy** [comment]
> I believe adding these information in a README.MD file would be perfect so in order to run the project in Vs, make sure to have the most recent versions or something like that 😍

@mahyoussef Totally agree, will submit a new PR with a README.md for C# Folder with the prerequisites for running the solution.

**Pull request merged**
